services:
  postgres:
    image: postgis/postgis:16-3.5-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/zimdev/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=zimdev
